project:
  type: website
  output-dir: docs

website:
  title: "Ry Shoots ðŸ“¸"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - text: Posts
        menu: 
          - href: post1.qmd
          - href: post2.qmd
          - href: post3.qmd
      - archive.qmd
    right: 
      - contact.qmd
  
          
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
    toc: true



